import type { ModelInfo } from "./interfaces/model-info.interface.js";

export const STATIC_MODELS: readonly ModelInfo[] = [
  // ── OpenAI ──────────────────────────────────────────────────
  {
    id: "gpt-4.1",
    provider: "openai",
    displayName: "GPT-4.1",
    status: "active",
    capabilities: { streaming: true, toolCalling: true, vision: true, embeddings: false, imageGeneration: false, audio: false, reasoning: false , functionCalling: false, moderation: false},
    pricing: { inputPerToken: 0.000002, outputPerToken: 0.000008, cachedInputPerToken: 0.0000005 },
    limits: { contextWindow: 1_047_576, maxOutputTokens: 32_768 },
    enabled: true,
    deprecated: false,
  },
  {
    id: "gpt-4.1-mini",
    provider: "openai",
    displayName: "GPT-4.1 Mini",
    status: "active",
    capabilities: { streaming: true, toolCalling: true, vision: true, embeddings: false, imageGeneration: false, audio: false, reasoning: false , functionCalling: false, moderation: false},
    pricing: { inputPerToken: 0.0000004, outputPerToken: 0.0000016, cachedInputPerToken: 0.0000001 },
    limits: { contextWindow: 1_047_576, maxOutputTokens: 32_768 },
    enabled: true,
    deprecated: false,
  },
  {
    id: "gpt-4.1-nano",
    provider: "openai",
    displayName: "GPT-4.1 Nano",
    status: "active",
    capabilities: { streaming: true, toolCalling: false, vision: false, embeddings: false, imageGeneration: false, audio: false, reasoning: false , functionCalling: false, moderation: false},
    pricing: { inputPerToken: 0.0000001, outputPerToken: 0.0000004, cachedInputPerToken: 0.000000025 },
    limits: { contextWindow: 1_047_576, maxOutputTokens: 32_768 },
    enabled: true,
    deprecated: false,
  },
  {
    id: "gpt-4o",
    provider: "openai",
    displayName: "GPT-4o",
    status: "active",
    capabilities: { streaming: true, toolCalling: true, vision: true, embeddings: false, imageGeneration: true, audio: true, reasoning: false , functionCalling: false, moderation: false},
    pricing: { inputPerToken: 0.0000025, outputPerToken: 0.00001, cachedInputPerToken: 0.00000125 },
    limits: { contextWindow: 128_000, maxOutputTokens: 16_384 },
    enabled: true,
    deprecated: false,
  },
  {
    id: "gpt-4o-mini",
    provider: "openai",
    displayName: "GPT-4o Mini",
    status: "active",
    capabilities: { streaming: true, toolCalling: true, vision: true, embeddings: false, imageGeneration: false, audio: false, reasoning: false , functionCalling: false, moderation: false},
    pricing: { inputPerToken: 0.00000015, outputPerToken: 0.0000006, cachedInputPerToken: 0.000000075 },
    limits: { contextWindow: 128_000, maxOutputTokens: 16_384 },
    enabled: true,
    deprecated: false,
  },
  {
    id: "o3",
    provider: "openai",
    displayName: "o3",
    status: "active",
    capabilities: { streaming: true, toolCalling: true, vision: true, embeddings: false, imageGeneration: false, audio: false, reasoning: true , functionCalling: false, moderation: false},
    pricing: { inputPerToken: 0.00001, outputPerToken: 0.00004, cachedInputPerToken: 0.0000025 },
    limits: { contextWindow: 200_000, maxOutputTokens: 100_000 },
    enabled: true,
    deprecated: false,
  },
  {
    id: "o4-mini",
    provider: "openai",
    displayName: "o4-mini",
    status: "active",
    capabilities: { streaming: true, toolCalling: true, vision: true, embeddings: false, imageGeneration: false, audio: false, reasoning: true , functionCalling: false, moderation: false},
    pricing: { inputPerToken: 0.0000011, outputPerToken: 0.0000044, cachedInputPerToken: 0.00000055 },
    limits: { contextWindow: 200_000, maxOutputTokens: 100_000 },
    enabled: true,
    deprecated: false,
  },
  {
    id: "gpt-4.5-preview",
    provider: "openai",
    displayName: "GPT-4.5 Preview",
    status: "active",
    capabilities: { streaming: true, toolCalling: true, vision: true, embeddings: false, imageGeneration: false, audio: false, reasoning: false , functionCalling: false, moderation: false},
    pricing: { inputPerToken: 0.000075, outputPerToken: 0.00015, cachedInputPerToken: 0.0000375 },
    limits: { contextWindow: 128_000, maxOutputTokens: 16_384 },
    enabled: true,
    deprecated: false,
  },

  // ── Anthropic ──────────────────────────────────────────────
  {
    id: "claude-sonnet-4",
    provider: "anthropic",
    displayName: "Claude Sonnet 4",
    status: "active",
    capabilities: { streaming: true, toolCalling: true, vision: true, embeddings: false, imageGeneration: false, audio: false, reasoning: false , functionCalling: false, moderation: false},
    pricing: { inputPerToken: 0.000003, outputPerToken: 0.000015, cachedInputPerToken: 0.0000003 },
    limits: { contextWindow: 200_000, maxOutputTokens: 8_192 },
    enabled: true,
    deprecated: false,
  },
  {
    id: "claude-haiku-3.5",
    provider: "anthropic",
    displayName: "Claude Haiku 3.5",
    status: "active",
    capabilities: { streaming: true, toolCalling: true, vision: true, embeddings: false, imageGeneration: false, audio: false, reasoning: false , functionCalling: false, moderation: false},
    pricing: { inputPerToken: 0.0000008, outputPerToken: 0.000004, cachedInputPerToken: 0.00000008 },
    limits: { contextWindow: 200_000, maxOutputTokens: 8_192 },
    enabled: true,
    deprecated: false,
  },
  {
    id: "claude-opus-4",
    provider: "anthropic",
    displayName: "Claude Opus 4",
    status: "active",
    capabilities: { streaming: true, toolCalling: true, vision: true, embeddings: false, imageGeneration: false, audio: false, reasoning: true , functionCalling: false, moderation: false},
    pricing: { inputPerToken: 0.000015, outputPerToken: 0.000075, cachedInputPerToken: 0.0000015 },
    limits: { contextWindow: 200_000, maxOutputTokens: 8_192 },
    enabled: true,
    deprecated: false,
  },

  // ── Gemini ────────────────────────────────────────────────
  {
    id: "gemini-2.5-pro",
    provider: "gemini",
    displayName: "Gemini 2.5 Pro",
    status: "active",
    capabilities: { streaming: true, toolCalling: true, vision: true, embeddings: true, imageGeneration: false, audio: true, reasoning: true , functionCalling: false, moderation: false},
    pricing: { inputPerToken: 0.00000125, outputPerToken: 0.00001, cachedInputPerToken: 0.00000003125 },
    limits: { contextWindow: 1_048_576, maxOutputTokens: 8_192 },
    enabled: true,
    deprecated: false,
  },
  {
    id: "gemini-2.5-flash",
    provider: "gemini",
    displayName: "Gemini 2.5 Flash",
    status: "active",
    capabilities: { streaming: true, toolCalling: true, vision: true, embeddings: true, imageGeneration: false, audio: true, reasoning: false , functionCalling: false, moderation: false},
    pricing: { inputPerToken: 0.00000015, outputPerToken: 0.0000006, cachedInputPerToken: 0.00000000375 },
    limits: { contextWindow: 1_048_576, maxOutputTokens: 8_192 },
    enabled: true,
    deprecated: false,
  },

  // ── OpenRouter ────────────────────────────────────────────
  {
    id: "openrouter/auto",
    provider: "openrouter",
    displayName: "OpenRouter Auto",
    status: "active",
    capabilities: { streaming: true, toolCalling: true, vision: true, embeddings: false, imageGeneration: false, audio: false, reasoning: false , functionCalling: false, moderation: false},
    pricing: { inputPerToken: 0, outputPerToken: 0 },
    limits: { contextWindow: 128_000, maxOutputTokens: 16_384 },
    enabled: true,
    deprecated: false,
  },
  {
    id: "anthropic/claude-sonnet-4",
    provider: "openrouter",
    displayName: "OpenRouter Claude Sonnet 4",
    status: "active",
    capabilities: { streaming: true, toolCalling: true, vision: true, embeddings: false, imageGeneration: false, audio: false, reasoning: false , functionCalling: false, moderation: false},
    pricing: { inputPerToken: 0.000003, outputPerToken: 0.000015, cachedInputPerToken: 0.0000003 },
    limits: { contextWindow: 200_000, maxOutputTokens: 8_192 },
    enabled: true,
    deprecated: false,
  },
  {
    id: "openai/gpt-4o",
    provider: "openrouter",
    displayName: "OpenRouter GPT-4o",
    status: "active",
    capabilities: { streaming: true, toolCalling: true, vision: true, embeddings: false, imageGeneration: false, audio: false, reasoning: false , functionCalling: false, moderation: false},
    pricing: { inputPerToken: 0.0000025, outputPerToken: 0.00001, cachedInputPerToken: 0.00000125 },
    limits: { contextWindow: 128_000, maxOutputTokens: 16_384 },
    enabled: true,
    deprecated: false,
  },

  // ── DeepSeek ──────────────────────────────────────────────
  {
    id: "deepseek-chat",
    provider: "deepseek",
    displayName: "DeepSeek Chat",
    status: "active",
    capabilities: { streaming: true, toolCalling: false, vision: false, embeddings: false, imageGeneration: false, audio: false, reasoning: false , functionCalling: false, moderation: false},
    pricing: { inputPerToken: 0.00000014, outputPerToken: 0.00000028, cachedInputPerToken: 0.000000014 },
    limits: { contextWindow: 64_000, maxOutputTokens: 8_192 },
    enabled: true,
    deprecated: false,
  },
  {
    id: "deepseek-reasoner",
    provider: "deepseek",
    displayName: "DeepSeek Reasoner",
    status: "active",
    capabilities: { streaming: true, toolCalling: false, vision: false, embeddings: false, imageGeneration: false, audio: false, reasoning: true , functionCalling: false, moderation: false},
    pricing: { inputPerToken: 0.00000055, outputPerToken: 0.00000219, cachedInputPerToken: 0.000000055 },
    limits: { contextWindow: 64_000, maxOutputTokens: 8_192 },
    enabled: true,
    deprecated: false,
  },

  // ── Mistral ───────────────────────────────────────────────
  {
    id: "mistral-large-latest",
    provider: "mistral",
    displayName: "Mistral Large",
    status: "active",
    capabilities: { streaming: true, toolCalling: true, vision: true, embeddings: false, imageGeneration: false, audio: false, reasoning: false , functionCalling: false, moderation: false},
    pricing: { inputPerToken: 0.000002, outputPerToken: 0.000006, cachedInputPerToken: 0.000001 },
    limits: { contextWindow: 128_000, maxOutputTokens: 8_192 },
    enabled: true,
    deprecated: false,
  },
  {
    id: "mistral-small-latest",
    provider: "mistral",
    displayName: "Mistral Small",
    status: "active",
    capabilities: { streaming: true, toolCalling: true, vision: false, embeddings: false, imageGeneration: false, audio: false, reasoning: false , functionCalling: false, moderation: false},
    pricing: { inputPerToken: 0.000001, outputPerToken: 0.000003, cachedInputPerToken: 0.0000005 },
    limits: { contextWindow: 32_000, maxOutputTokens: 8_192 },
    enabled: true,
    deprecated: false,
  },
  {
    id: "codestral-latest",
    provider: "mistral",
    displayName: "Codestral",
    status: "active",
    capabilities: { streaming: true, toolCalling: true, vision: false, embeddings: false, imageGeneration: false, audio: false, reasoning: false , functionCalling: false, moderation: false},
    pricing: { inputPerToken: 0.000001, outputPerToken: 0.000003, cachedInputPerToken: 0.0000005 },
    limits: { contextWindow: 256_000, maxOutputTokens: 8_192 },
    enabled: true,
    deprecated: false,
  },

  // ── Groq ──────────────────────────────────────────────────
  {
    id: "llama-4-scout-17b-16e-instruct",
    provider: "groq",
    displayName: "Llama 4 Scout",
    status: "active",
    capabilities: { streaming: true, toolCalling: true, vision: true, embeddings: false, imageGeneration: false, audio: false, reasoning: false , functionCalling: false, moderation: false},
    pricing: { inputPerToken: 0, outputPerToken: 0 },
    limits: { contextWindow: 1_000_000, maxOutputTokens: 8_192 },
    enabled: true,
    deprecated: false,
  },
  {
    id: "llama-3.3-70b-versatile",
    provider: "groq",
    displayName: "Llama 3.3 70B",
    status: "active",
    capabilities: { streaming: true, toolCalling: true, vision: false, embeddings: false, imageGeneration: false, audio: false, reasoning: false , functionCalling: false, moderation: false},
    pricing: { inputPerToken: 0, outputPerToken: 0 },
    limits: { contextWindow: 128_000, maxOutputTokens: 32_768 },
    enabled: true,
    deprecated: false,
  },
  {
    id: "mixtral-8x7b-32768",
    provider: "groq",
    displayName: "Mixtral 8x7B",
    status: "active",
    capabilities: { streaming: true, toolCalling: false, vision: false, embeddings: false, imageGeneration: false, audio: false, reasoning: false , functionCalling: false, moderation: false},
    pricing: { inputPerToken: 0, outputPerToken: 0 },
    limits: { contextWindow: 32_768, maxOutputTokens: 8_192 },
    enabled: true,
    deprecated: false,
  },

  // ── xAI ───────────────────────────────────────────────────
  {
    id: "grok-3",
    provider: "xai",
    displayName: "Grok 3",
    status: "active",
    capabilities: { streaming: true, toolCalling: true, vision: true, embeddings: false, imageGeneration: false, audio: false, reasoning: true , functionCalling: false, moderation: false},
    pricing: { inputPerToken: 0.000003, outputPerToken: 0.000015 },
    limits: { contextWindow: 131_072, maxOutputTokens: 8_192 },
    enabled: true,
    deprecated: false,
  },
  {
    id: "grok-3-mini",
    provider: "xai",
    displayName: "Grok 3 Mini",
    status: "active",
    capabilities: { streaming: true, toolCalling: true, vision: false, embeddings: false, imageGeneration: false, audio: false, reasoning: true , functionCalling: false, moderation: false},
    pricing: { inputPerToken: 0.0000003, outputPerToken: 0.0000005 },
    limits: { contextWindow: 131_072, maxOutputTokens: 8_192 },
    enabled: true,
    deprecated: false,
  },

  // ── Ollama (common models) ─────────────────────────────────
  {
    id: "llama3.2",
    provider: "ollama",
    displayName: "Llama 3.2",
    status: "active",
    capabilities: { streaming: true, toolCalling: false, vision: false, embeddings: false, imageGeneration: false, audio: false, reasoning: false , functionCalling: false, moderation: false},
    pricing: { inputPerToken: 0, outputPerToken: 0 },
    limits: { contextWindow: 128_000, maxOutputTokens: 8_192 },
    enabled: true,
    deprecated: false,
  },
  {
    id: "llama3.2-vision",
    provider: "ollama",
    displayName: "Llama 3.2 Vision",
    status: "active",
    capabilities: { streaming: true, toolCalling: false, vision: true, embeddings: false, imageGeneration: false, audio: false, reasoning: false , functionCalling: false, moderation: false},
    pricing: { inputPerToken: 0, outputPerToken: 0 },
    limits: { contextWindow: 128_000, maxOutputTokens: 8_192 },
    enabled: true,
    deprecated: false,
  },
  {
    id: "llama3.1",
    provider: "ollama",
    displayName: "Llama 3.1",
    status: "active",
    capabilities: { streaming: true, toolCalling: true, vision: false, embeddings: false, imageGeneration: false, audio: false, reasoning: false , functionCalling: false, moderation: false},
    pricing: { inputPerToken: 0, outputPerToken: 0 },
    limits: { contextWindow: 128_000, maxOutputTokens: 8_192 },
    enabled: true,
    deprecated: false,
  },
  {
    id: "mistral",
    provider: "ollama",
    displayName: "Mistral",
    status: "active",
    capabilities: { streaming: true, toolCalling: false, vision: false, embeddings: false, imageGeneration: false, audio: false, reasoning: false , functionCalling: false, moderation: false},
    pricing: { inputPerToken: 0, outputPerToken: 0 },
    limits: { contextWindow: 32_768, maxOutputTokens: 8_192 },
    enabled: true,
    deprecated: false,
  },
  {
    id: "codellama",
    provider: "ollama",
    displayName: "Code Llama",
    status: "active",
    capabilities: { streaming: true, toolCalling: false, vision: false, embeddings: false, imageGeneration: false, audio: false, reasoning: false , functionCalling: false, moderation: false},
    pricing: { inputPerToken: 0, outputPerToken: 0 },
    limits: { contextWindow: 16_384, maxOutputTokens: 8_192 },
    enabled: true,
    deprecated: false,
  },
  {
    id: "mixtral",
    provider: "ollama",
    displayName: "Mixtral",
    status: "active",
    capabilities: { streaming: true, toolCalling: false, vision: false, embeddings: false, imageGeneration: false, audio: false, reasoning: false , functionCalling: false, moderation: false},
    pricing: { inputPerToken: 0, outputPerToken: 0 },
    limits: { contextWindow: 32_768, maxOutputTokens: 8_192 },
    enabled: true,
    deprecated: false,
  },
  {
    id: "gemma2",
    provider: "ollama",
    displayName: "Gemma 2",
    status: "active",
    capabilities: { streaming: true, toolCalling: false, vision: false, embeddings: false, imageGeneration: false, audio: false, reasoning: false , functionCalling: false, moderation: false},
    pricing: { inputPerToken: 0, outputPerToken: 0 },
    limits: { contextWindow: 8_192, maxOutputTokens: 8_192 },
    enabled: true,
    deprecated: false,
  },
];
