// This file is auto-generated by openapi-typescript.
// Run `pnpm generate` or `bash scripts/generate-api-types.sh` to regenerate.
// Generated from: services/backend/openapi.json
// Custom overrides for endpoints returning Promise<unknown>

import type { paths as GeneratedPaths } from "./types.openapi";

export type paths = GeneratedPaths;

// Manual type overrides for endpoints without OpenAPI response schemas
// These are documented in TASK-1125 — many controllers return Promise<unknown>

export interface DocumentListResponse {
  id: string;
  filename: string;
  mimeType: string;
  size: number;
  status: string;
  createdAt: string;
  updatedAt: string;
}

export interface MetadataResponse {
  id: string;
  documentId: string;
  key: string;
  value: string;
  createdAt: string;
}

export interface OcrResultResponse {
  id: string;
  documentId: string;
  status: string;
  text: string;
  confidence: number;
  createdAt: string;
}

export interface ParserResultResponse {
  id: string;
  documentId: string;
  status: string;
  content: string;
  createdAt: string;
}

export interface PromptLibraryResponse {
  id: string;
  name: string;
  description: string;
  category: string;
  status: "draft" | "published" | "archived";
  version: number;
  createdAt: string;
  updatedAt: string;
}
