export enum AiGatewayErrorCode {
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  INVALID_REQUEST = "INVALID_REQUEST",
  MODEL_NOT_ALLOWED = "MODEL_NOT_ALLOWED",
  PROVIDER_NOT_ENABLED = "PROVIDER_NOT_ENABLED",
  PROVIDER_ERROR = "PROVIDER_ERROR",
  RATE_LIMITED = "RATE_LIMITED",
  QUOTA_EXCEEDED = "QUOTA_EXCEEDED",
}
