import type { OrganizationSettings } from "../interfaces/organization-settings.interface.js";

export const DEFAULT_ORGANIZATION_SETTINGS: OrganizationSettings = {
  security: {
    sessionTimeoutMinutes: 60,
    requireMfa: false,
    allowedIpRanges: [],
    allowedEmailDomains: [],
    maximumLoginAttempts: 5,
  },
  authentication: {
    allowedProviders: ["email"],
    defaultProvider: "email",
    enableRegistration: true,
    enablePasswordReset: true,
    enableSessionManagement: true,
  },
  ai: {
    enabledProviders: [],
    blockedProviders: [],
    defaultProvider: null,
    allowedModels: [],
    blockedModels: [],
    maxInputTokens: null,
    maxOutputTokens: null,
    allowImageGeneration: false,
    allowAudioGeneration: false,
    allowEmbeddings: false,
    allowModeration: false,
    allowTools: false,
    allowMcp: false,
    allowRag: false,
    allowPromptTemplates: false,
    allowConversationMemory: false,
    allowStreaming: false,
  },
  storage: {
    maxStorageBytes: null,
    maxUploadSizeBytes: null,
    allowedFileTypes: [],
    blockedFileTypes: [],
    retentionDays: null,
    enableVersioning: false,
  },
  regional: {
    defaultLocale: "en-US",
    defaultTimezone: "UTC",
    allowedLocales: ["en-US"],
    dateFormat: "YYYY-MM-DD",
    timeFormat: "24h",
    firstDayOfWeek: 1,
    country: "US",
    region: "us-east",
    currency: "USD",
    language: "en",
    legalRegion: "US",
    billingRegion: "US",
    paymentRegion: "US",
    privacyRegion: "US",
    dataResidencyRegion: "US",
  },
  featureFlags: {},
  billing: {
    enabledProviders: [],
    defaultCurrency: "USD",
    billingEmail: null,
    invoicePrefix: null,
    taxId: null,
    paymentTermsDays: 30,
    autoInvoicing: false,
    currency: {},
  },
};
